# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cherryctl < Formula
  desc "Official Cherry Servers CLI"
  homepage "https://www.cherryservers.com/"
  version "0.8.0"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cherryservers/cherryctl/releases/download/v0.8.0/cherryctl-darwin-amd64"
      sha256 "5a40d67f8883ba28b11ac143a1854f5be1c536e68750a8f7fe81d50981e990c9"

      def install
        bin.install "cherryctl-darwin-amd64" => "cherryctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cherryservers/cherryctl/releases/download/v0.8.0/cherryctl-darwin-arm64"
      sha256 "55adf0c21f3e76c563d0b4746636f5640f549d9e40486defb678e9f51b285112"

      def install
        bin.install "cherryctl-darwin-arm64" => "cherryctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cherryservers/cherryctl/releases/download/v0.8.0/cherryctl-linux-amd64"
      sha256 "572abace2c682670776c9c45cea729f6b5ee5afc43cb23a74a73d9eeaf9ee49c"
      def install
        bin.install "cherryctl-linux-amd64" => "cherryctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cherryservers/cherryctl/releases/download/v0.8.0/cherryctl-linux-arm64"
      sha256 "195121c36f4ecd545389eb78c2acde4230ae9cee660e483baef4384d0c2dafb7"
      def install
        bin.install "cherryctl-linux-arm64" => "cherryctl"
      end
    end
  end

  test do
    system "#{bin}/cherryctl -v"
  end
end
