# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cherryctl < Formula
  desc "Official Cherry Servers CLI"
  homepage "https://www.cherryservers.com/"
  version "0.4.1"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/cherryservers/cherryctl/releases/download/v0.4.1/cherryctl-darwin-amd64"
      sha256 "490211a1f6ef9406bfdff8e590cb998d8210d0f632f9b5806f075b25be440e9b"

      def install
        bin.install "cherryctl-darwin-amd64" => "cherryctl"
      end
    end
    on_arm do
      url "https://github.com/cherryservers/cherryctl/releases/download/v0.4.1/cherryctl-darwin-arm64"
      sha256 "4f97d018b90f1c175c932b7df224b34a87b6b887df99fc0cf07e37d003eb1012"

      def install
        bin.install "cherryctl-darwin-arm64" => "cherryctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cherryservers/cherryctl/releases/download/v0.4.1/cherryctl-linux-amd64"
        sha256 "c7319cbe55ad9aac8c53e8efd777473de389315698b6f572b678937397214409"

        def install
          bin.install "cherryctl-linux-amd64" => "cherryctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cherryservers/cherryctl/releases/download/v0.4.1/cherryctl-linux-arm64"
        sha256 "1f2fd6f4f876921a4fd586c705fd6ad8dbe785d78f20656521c44a2757db3944"

        def install
          bin.install "cherryctl-linux-arm64" => "cherryctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cherryctl -v"
  end
end
